node:
  coordinates: 
    1: [-4.5, 2.5]
    2: [-3, 3.5]
    3: [-2.8, 2.5]
    4: [-1.8, 2.6]
    5: [-0.5, 2.5]
    6: [-1.4, 1.8]
    7: [-0.5, 0.5]
    8: [1.2, 2.5]
    9: [2.5, 2.8]
    10: [3.8, 3]
    11: [3.8, 2]
    12: [2.2, 2]
    13: [4, 1]
    14: [1.8, 0.5]
    15: [3.1, 0]
    16: [3, -1]
    17: [1.2, -1]
    18: [1.1, -2.2]
    19: [2.5, -1.6]
    20: [3.5, -2]
    21: [2.5, -2.5]
    22: [2, -3]
    23: [-0.4, -2.5]
    24: [0.2, -0.5]
    25: [-1.1, -1.8]
    26: [-1.8, -2.5]
    27: [-3, -1.6]
    28: [-3, -2.5]
    29: [-3.8, -1.8]
    30: [-3.8, -0.9]
    31: [-3.8, 0.5]
    32: [-3, 1.8]

  edges: 
    - [1, 2]
    - [1, 32]
    - [2, 3]
    - [2, 4]
    - [3, 4]
    - [3, 32]
    - [4, 5]
    - [4, 6]
    - [5, 6]
    - [5, 8]
    - [6, 7]
    - [6, 32]
    - [7, 17]
    - [8, 9]
    - [8, 12]
    - [9, 10]
    - [9, 12]
    - [10, 11]
    - [11, 12]
    - [11, 13]
    - [12, 14]
    - [13, 15]
    - [14, 24]
    - [14, 15]
    - [15, 16]
    - [16, 17]
    - [16, 19]
    - [16, 20]
    - [17, 19]
    - [17, 18]
    - [18, 21]
    - [18, 22]
    - [18, 23]
    - [19, 21]
    - [20, 21]
    - [21, 22]
    - [23, 25]
    - [23, 26]
    - [24, 25]
    - [25, 26]
    - [26, 28]
    - [25, 27]
    - [27, 28]
    - [27, 29]
    - [27, 30]
    - [28, 29]
    - [29, 30]
    - [30, 31]
    - [31, 32]


markov_chain:
  damages : [0.01,0.02,0.03,0.05]


node_count: 32


  


icons:
  0: 'icons/damage_level_0.png'
  1: 'icons/damage_level_1.png'
  2: 'icons/damage_level_2.png'
  3: 'icons/damage_level_3.png'
  4: 'icons/damage_level_4.png'

simu_n : 200